parameters:
    # Adds a fallback DATABASE_URL if the env var is not set.
    # This allows you to run cache:warmup even if your
    # environment variables are not available yet.
    # You should not need to change this value.
    env(DATABASE_URL): ''

doctrine:
    dbal:
        # configure these for your database server
        #driver: 'pdo_mysql'
        #server_version: '5.7'
        #charset: utf8mb4
        #default_table_options:
        #    charset: utf8mb4
        #    collate: utf8mb4_unicode_ci

        #url: '%env(resolve:DATABASE_URL)%'
        default_connection: intranet
        connections:
            crm:
                # configure these for your database server
                url: '%env(DATABASE_URL)%'
                driver: 'pdo_mysql'
                server_version: '5.7'
                charset: utf8mb4
                mapping_types:
                    enum: string
                #collate: utf8mb4_unicode_ci
            intranet:
                # configure these for your database server
                url: '%env(DATABASE_INTRANET_URL)%'
                driver: 'pdo_mysql'
                server_version: '5.7'
                charset: utf8mb4
                mapping_types:
                    enum: string
                #collate: utf8mb4_unicode_ci
    orm:
        #auto_generate_proxy_classes: true
        #naming_strategy: doctrine.orm.naming_strategy.underscore
        #auto_mapping: true
        #mappings:
        #    App:
        #        is_bundle: false
        #        type: annotation
        #        dir: '%kernel.project_dir%/src/Entity'
        #        prefix: 'App\Entity'
        #        alias: App
        default_entity_manager: intranet
        entity_managers:
            intranet:
                connection: intranet
                mappings:
                    intranet:
                        is_bundle: false
                        type: annotation
                        dir: '%kernel.project_dir%/src/Entity'
                        prefix: 'App\Entity'
                        alias: intranet
            crm:
                connection: crm
                mappings:
                    crm:
                        is_bundle: false
                        type: annotation
                        dir: '%kernel.project_dir%/src/Entity'
                        prefix: 'App\Entity'
                        alias: crm