#index:
#    path: /
#    controller: App\Controller\DefaultController::index
app_logout:
    path: /logout
    methods: GET
app_lucky_number:
    path: /lucky/number
    controller: App\Controller\LuckyController::number
app_factura:
    path: /facturas
    controller: App\Controller\FacturaController::index
app_homepage:
    path: /
    controller: App\Controller\DefaultController::index